import './global.css';

export const metadata = {
  title: 'Welcome to mikntech-tl',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta http-equiv="refresh" content="1;url=https://mikntech.com" />
      </head>
      <body>{children}</body>
    </html>
  );
}
