import './global.css';
import { PostHogProvider } from './providers';

export const metadata = {
  title: 'Welcome to mikntech-mn',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PostHogProvider>
        <body>{children}</body>
      </PostHogProvider>
    </html>
  );
}
