name: Build and Publish Libraries
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main  # Trigger only on the main branch

jobs:
  build-and-publish-libs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    strategy:
      matrix:
        library: [lib1, lib2, lib3]  # Replace with actual library directories
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0  # Required for pull request analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Sync versions
        run: npm run sync-versions

      - name: Build ${{ matrix.library }}
        run: |
          nx build ${{ matrix.library }}

      - name: Publish ${{ matrix.library }}
        run: |
          mkdir -p ~/.npm
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_C }}" > ~/.npmrc
          npm publish dist/libs/${{ matrix.library }} --access public
