name: Build and Publish Libraries
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  detect-libraries:
    runs-on: ubuntu-latest
    outputs:
      libraries: ${{ steps.get_libs.outputs.libs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find libraries in libs/ directory
        id: get_libs
        run: |
          LIBS=$(find libs/* -maxdepth 0 -type d -exec basename {} \;)
          if [ -z "$LIBS" ]; then
            echo "No libraries found!"
            exit 1
          fi
          LIBS_JSON=$(echo "[\"$(echo $LIBS | sed 's/ /\",\"/g')\"]")
          echo "Found libraries: $LIBS_JSON"
          echo "::set-output name=libs::$LIBS_JSON"

  build-and-publish-libs:
    runs-on: ubuntu-latest
    needs: detect-libraries
    strategy:
      matrix:
        library: ${{ fromJson(needs.detect-libraries.outputs.libraries) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Sync versions
        run: npm run sync-versions

      - name: Bump version for ${{ matrix.library }}
        run: |
          cd libs/${{ matrix.library }}
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          git config --global user.email "mnpcmw6444+cicd@gmail.com"
          git config --global user.name "Version Bump"
          git commit -am "CI/CD Version bump to $NEW_VERSION for ${{ matrix.library }} [skip ci]"
          git tag v${NEW_VERSION}
          cd ../..

      - name: Build ${{ matrix.library }}
        run: |
          npx nx build ${{ matrix.library }}

      - name: Authenticate to npm for ${{ matrix.library }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_C }}" > ~/.npmrc

      - name: Publish ${{ matrix.library }}
        run: |
          cd dist/libs/${{ matrix.library }}
          npm publish --access public
          cd ../../..
