name: Build and Publish
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main  # Trigger only on main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    strategy:
      matrix:
        task: [build, publish]  # Running build and publish in parallel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0  # Required for pull request analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci  # Faster than npm install as it uses the package-lock.json

      - name: Sync versions
        run: npm run sync-versions

      - name: Run ${{ matrix.task }} task
        run: |
          if [ "${{ matrix.task }}" == "build" ]; then
            npm run build
          elif [ "${{ matrix.task }}" == "publish" ]; then
            mkdir -p ~/.npm
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_C }}" > ~/.npmrc
            npm run publish-all
          fi

  bump-version:
    runs-on: ubuntu-latest
    needs: build-and-publish  # Ensure version bump runs after build and publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0  # Required for pull request analysis

      - name: Bump version in package.json
        run: |
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          git config --global user.email "mnpcmw6444+cicd@gmail.com"
          git config --global user.name "Version Bump"
          git commit -am "CI/CD Version auto-increment to $NEW_VERSION [skip ci]"
          git tag v$NEW_VERSION
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git push git@github.com:${{ github.repository }} HEAD:${{ github.ref_name }}
