name: Build and Publish
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Bump version in package.json
        run: |
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          git config --global user.email "mnpcmw6444+cicd@gmail.com"
          git config --global user.name "Version Bump"
          git commit -am "CI/CD Version auto-increment to $NEW_VERSION [skip ci]"
          git tag v$NEW_VERSION
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git push git@github.com:${{ github.repository }} HEAD:${{ github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Authenticate to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_C }}" > ~/.npmrc

      - name: Build and Publish
        run: npm run build-and-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_C }}
